Inventorying Your Collection
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Initial Set Up
^^^^^^^^^^^^^^

. Record the date you start inventory on.  You will need this when running reports later in the process.
. In Evergreen, xref:_cloning_a_report_template[clone the Sitka report templates] called _Inventory - Un-scanned Items_ and _Inventory - 
Scanned Items Count by Shelving Location_. Both templates can be found under 
Sitka_templates -> Inventory.
. In Evergreen, go to **Circulation -> Check In**.
.. From the _Checkin Modifiers_ drop down select **Update Inventory**.
.. Ensure this is done on all computers where items may be checked in.

This ensures that any items currently circulating will have their inventory date updated when they are checked in.

Workflow - Item Status
^^^^^^^^^^^^^^^^^^^^^^

. Go to **Circulation -> Item Status**.
. Ensure you have rows set to at least 50.
. Scan in your items.
. Select all the items by clicking on the check box in the column label row.
. From the **Actions** menu choose **Update Inventory**.
. A confirmation will appear in the bottom right corner.
. Repeat until you have scanned and updated all items in your desired section of your collection.
. Run a report using the Sitka Template _Inventory - Un-scanned Items_.  You will need the date you started 
inventory on and the shelving location(s) you did for the filters when running the report.
. Take the list of un-scanned items the report produces and check the shelves to see if any were missed.
. Scan in any missed items and update their inventory date.
. Set the remaining items on the list to have a status of _Missing_.  This can be done in batch through
the Items Status screen.
. Run a report using the Sitka Template _Inventory - Scanned Items Count by Shelving Location_. You will need 
the date you started inventory on for the filter when running the report.
. This report will show you how many items have had their inventory date updated since you started inventory.  You 
will likely see items from other shelving locations that have been updated through your regular check in process.
. Repeat all the steps for every shelving location/section of your collection that you wish to inventory.

Workflow - Check In
^^^^^^^^^^^^^^^^^^^

. Go to **Circulation -> Check In**.
. Ensure the checkin modifier **Update Inventory** is active.
. Scan in your items.
. Repeat until you have scanned and updated all items in your desired section of your collection.
. Run a report using the Sitka Template _Inventory - Un-scanned Items_.  You will need the date you started 
inventory on and the shelving location(s) you did for the filters when running the report.
. Take the list of un-scanned items the report produces and check the shelves to see if any were missed.
. Scan in any missed items and update their inventory date.
. Set the remaining items on the list to have a status of _Missing_.  This can be done in batch through
the Items Status screen.
. Run a report using the Sitka Template _Inventory - Scanned Items Count by Shelving Location_. You will need 
the date you started inventory on for the filter when running the report.
. This report will show you how many items have had their inventory date updated since you started inventory.  You 
will likely see items from other shelving locations that have been updated through your regular check in process.
. Repeat all the steps for every shelving location/section of your collection that you wish to inventory.

Workflow - Portable Barcode Scanner
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

. Using your portable barcode scanner, scan every item on the shelf in the chosen area.
. Export the barcodes to a text file (we recommend using Notepad) and save the file. The barcodes should be in one single spaced single column without extra spaces anywhere.
. Use Cut and Paste functions to break the big list of barcodes into smaller lists and save each list as an
individual text file (we recommend each list contains under 500 barcodes). Name your files in sequence, e.g.
inventory001, inventory002..., so that it will be easy to follow when you upload the files.
. Go to **Circulation -> Item Status**.
. Ensure you have rows set to at least 500.
. Click **Choose File**.
. You will be prompted to browse your local computer to find the barcode files. Navigate to and select your
first file and click **Open**.
. Every item on the list is retrieved and displayed. It may take a while if the list is long. 
. Select all items using the checkbox at the top of the Row Selector Column.
. From the **Actions** menu choose **Update Inventory**.
. A confirmation will appear in the bottom right corner.
. Repeat until you have updated all items in your desired section of your collection.
. Run a report using the Sitka Template _Inventory - Un-scanned Items_.  You will need the date you started 
inventory on and the shelving location(s) you did for the filters when running the report.
. Take the list of un-scanned items the report produces and check the shelves to see if any were missed.
. Scan in any missed items and update their inventory date.
. Set the remaining items on the list to have a status of _Missing_.  This can be done in batch through
the Items Status screen.
. Run a report using the Sitka Template _Inventory - Scanned Items Count by Shelving Location_. You will need 
the date you started inventory on for the filter when running the report.
. This report will show you how many items have had their inventory date updated since you started inventory.  You 
will likely see items from other shelving locations that have been updated through your regular check in process.
. Repeat all the steps for every shelving location/section of your collection that you wish to inventory.

Finishing Your Inventory
^^^^^^^^^^^^^^^^^^^^^^^^

Once you have inventoried all desired section of your collection, run the two inventory
reports one more time. Anything that still shows up on the un-scanned report should be set 
to missing.  The scanned item report will give you the final count of how many items
were inventoried.





////
ORIGINAL CONTENT

There are two report templates in the Sitka_templates -> Inventory folder on the _Reports_ screen.

**Inventory - Scanned Items Count by Shelving Location**

This report counts the items that have been checked in/out or otherwise had their status changed
(including being checked out, marked missing or lost) during the inventory period.
The date when you started taking inventory should be entered as the _Copy Status Changed Time_ when
running the report. The numbers are broken down by shelving locations.

**Inventory - Un-scanned Items**

This report generates a list of items that should be on the shelf but were not checked in/out
or otherwise had their status changed during the inventory period. When running the report use the
date when you started taking inventory for the _Copy Status Changed Time_, the shelving location(s) in which
you took inventory and the "on shelf" statuses _Reshelving_ and _Available_.

You can use this report to search for the listed items. You can also upload the barcodes from this report into the 
Item Status screen and set the items to _Missing_.


Running Inventory
-----------------

The following procedure was developed by Co-op Support based on the current functionality available
in Sitka's Evergreen,  and the experience of inventory projects done by libraries in the Sitka consortium and
the Evergreen community.

Inventory in Evergreen involves staff checking in all items in a specific area, using the Checkin Modifier Update Inventory, or, scanning or uploading barcodes to the Item Status screen, and batch editing the Update Inventory date. Staff can then run a report to list all the items that were not scanned, and look for them.

When items are inventoried,  the date, time, and workstation is recorded in
the Update Inventory  field of the item record. This field is used by the inventory reports to determine which items have been inventoried and which have not.

Preparing for Inventory
~~~~~~~~~~~~~~~~~~~~~~~

The first step to running inventory is to choose the section of your library you will inventory. We recommend
that you inventory a shelving location or particular call number range. There are several report templates
you can use to aid you in preparing for your inventory.

* Sitka_templates -> Collection -> Item and Title Count -> Title & 
Item Count by Shelving Location & Circulation Modifier
+
* Sitka_templates -> Collection -> Item List by Item Attributes -> 
Call Number : Items with Call Numbers within a Range
+
* Sitka_templates -> Collection -> Item List by Item Attributes -> Shelving Location : 
Items with Selected Shelving Location

[TIP]
=====
Once inventory starts, any item found in an incorrect location should be checked in before it is shelved
in the correct location.
=====

Running Inventory with the Staff Client
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

. In Evergreen go to **Circulation → Check In** or **Circulation → Item Status**.
+
. If using *Check in*, enable Checkin Modifier *Update Inventory*.
+
. Scan the items in.
+
. If using *Item Status*, select all items on screen and click **Actions → Update Inventory**.


[TIP]
=====
Staff can check for cataloguing issues while checking in items for inventory. To do so set up your Check In
screen with the following columns:

* Title
+
* Location
+
* Circulation Modifier
+
* Call Number

Staff can fix items right away or put them aside to be dealt with later.
=====

Running Inventory with the Offline Module
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If you are planning to take a laptop into your shelves and do not have Wi-Fi available you can use
Evergreen's Offline module to check items in for inventory.

. In Evergreen go to **Circulation → Offline Circulation**.
+
. Go to **Checkin** and check in the items in the area you are inventorying.
+
. Connect the computer to the internet and open the Evergreen Staff Client.
+
. Upload your check ins. See xref:_upload_and_process_offline_transactions[].
+
. Make sure you follow up on any exceptions that appear when the transactions are uploaded. See
xref:_handle_exceptions[]. These items will need to be pulled from the shelf and checked in on the live staff client to
resolve the exceptions.

Running Inventory with a Portable Barcode Scanner
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Some libraries have portable barcode scanners designed to be used for inventory.  These scanners collect and
store barcode information which can then be exported as a file and saved on a computer.

. Scan every item barcode on shelf in the chosen area.
+
. Export the barcodes to a text file (we recommend using Notepad) and save the file. The barcodes should be in one single spaced single column without extra spaces anywhere.
+
. Use Cut and Paste functions to break the big list of barcodes into smaller lists and save each list as an
individual text file (we recommend each list contains about 50 to 100 barcodes). Name your files in sequence, e.g.
inventory001, inventory002..., so that it will be easy to follow when you upload the files.
+
. On the Item Status screen in Evergreen, click **Choose File**.
+
. You will be prompted to browse your local computer to find the barcode files. Navigate to and select your
first file and click **Open**.
+
. Every item on the list is retrieved and displayed. It may take a while if the list is long. Select all
items using the checkbox at the top of the Row Selector Column.
+
. Click **Actions → Update Inventory**.
+
. Repeat steps 4-7 to inventory the items in all of your files.


[TIP]
=====
You may see prompt popups for items with special statuses, such as lost, missing, checked out,
in-transit or routing to the holds shelf. Once you confirm the prompt, the loading will continue.
You need to follow up with items going on hold shelf and in-transit.
=====

////