Introduction
~~~~~~~~~~~~

Evergreen's Offline Circulation interface is designed to log transactions during network outage. Transactions can be uploaded and processed once network operations are restored.

New in Evergreen version 3.1 you can choose how to save your offline transactions. You can use Chrome to save your transactions, or you can install and configure an Evergreen application called xref:download-hatch-ref[].

Save Offline Transactions in Chrome
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Chrome is simple to use and manage. *Offline Circulation* in the web client relies on the use of web service workers to store information for offline use. The web service workers will refresh the cache every *24 hours* under normal use.  Chrome uses cookies to save your transactions.

[CAUTION]
=============
* Do not delete browser cookies if you have pending offline transactions.
* Offline transactions must be uploaded as soon as possible as they will be cleared every *24 hours*
=============

Save Offline Transactions in Hatch
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

If you have Hatch running on your workstation you can use it to save your offline transactions.

. Log into Evergreen as LSA.
. Click *Administration -> Workstation*.
. Click *Print/Storage Service ('Hatch')*
. Make sure that you see that Hatch is available. Click *Store Offline Transaction Data in Hatch*.
. Log out.
. Offline Transactions will now be stored in Hatch. This will enable you to delete your browser cookies and not lose your offline transactions.
