Running Recurring Reports
-------------------------

Recurring reports are a useful way to save time by scheduling reports that you run on a regular basis, such as 
monthly circulation and monthly patron registration statistics. When you have set up a report to run on a 
monthly basis, you may request an email informing you that the report has successfully run. You can click on 
the link in the email that will take you directly to the report output. You can also access the output through 
the Reports interface as described in Chapter 30, Viewing Report Output.
 
To set up a monthly recurring report, follow the procedure in Generating Reports from Templates but make the 
changes described below.
 
. Select the Recurring Report check-box and set the recurrence interval to 1 month.
. Do not select Run ASAP. Instead schedule the report to run early on the first day of the next month. 
Enter the date in YYYY-MM-DD format.
. Ensure there is an email address to receive completion emails. You will receive an email completion notice 
each month when the output is ready.
. Select a folder for the report’s output.
. Click Save Report.
. You will get a confirmation dialogue box that the Action Succeeded. Click OK.
 
With the above settings, you will get an email on the first day of each month with a link to the report 
output. By clicking this link it will open the output in a web browser. It is still possible to login to 
the staff client and access the output in Output folder.
 
*Always use 'relative date' for recurring reports.* Date is a filter on nearly every template. When setting up 
a recurring report, always choose Relative Date, instead of Real Date for any date filter on the report 
creating screen. When using relative date the actual date will be calculated when the report runs. Unlike a 
real date, the actual value of relative date is adjusted according to the run time. For example, if the report 
runs at 2012-10-10 23:00, a relative date transformed to YYYY-MM of "1 month ago" will be Sept, 2012; while a 
relative date transformed to YYYY-MM-DD of '1 day ago" will be 2012-10-09. When it runs at 2012-11-10 23:00 
"1 month ago", it will be Oct, 2012, while "1 day ago" will be 2012-11-09. The date goes by calendar day 
or month.
 
*How to stop an existing recurring report?* To stop a recurring report, you may delete the pending output 
from Pending area in Output folder. You may also delete the report from Report folder. But deleting the report 
will delete all the output files generated by it, too.
 
*How to make changes to an existing recurring report?* Sometimes you may wish to make changes to a recurring 
report, e.g. the recurrence interval, generation date, email address to receive completion email, output 
format/folder or even filter values (such as the number of days overdue). You may do it by editing the report. 
See Viewing/Editing/Rescheduling Reports for details.
 
TIP: Report running interval should correspond to the date filter. For example, if the template filters 
on a date instead of month, a recurring report running with a monthly interval may miss a day or capture 
an extra day's data. So it works better if the filter can be transformed to month.
Schedule your monthly report to run early next month, but not at the end of the current month.
Once you have been on Evergreen for a year, you can set up your recurring monthly reports to show comparative 
data from one year ago. To do this select relative dates of 1 month ago and 13 months ago.
 




