Shared Sitka Templates
----------------------

CAUTION: Cloning templates created on the old staff client (XUL in ui column) may not work perfectly. You may need to remove, then put back some fields during cloning. 

The Sitka support team has created generic templates for commonly requested reports and shared them under 
the Sitka_templates folder. This chapter describes how to make local copies of these templates for 
routine reports or as a starting point for customization. When creating a new template it is a good idea 
to review the shared templates first: even if the exact template you need does not exist, it is often faster 
to modify an existing template than to build a brand new one. Reporter permissions are required to clone 
templates from the Shared Folders section and save them to My Folders.
 
What's in Sitka_templates
~~~~~~~~~~~~~~~~~~~~~~~~~

The Coop support team uses a dedicated staff account, Sitka_templates, to share ready-to-use templates. 
Below is what a user with reporter permissions can see after going to the Reports module, then follow the 
path to Shared Folders, click the arrow (or + sign) in front of Templates, and then Sitka_templates.
 
 
From Acquisitions to Serials are the subfolders containing various templates. Templates using 
the same source table are usually grouped together under one subfolder. These templates are created based 
on the anticipation that most libraries may need such reports. Coop support tends to make these templates 
generic, which means they contain more information. Individual libraries may have slightly different 
requirements. You can remove the unwanted information when cloning the templates or choose appropriate 
values for some filters to disable them. These templates are usually referred to as Sitka standard templates.
 
The following is a guideline of the templates for various kinds of reports. Please note that Coop support regularly maintains the templates. The list below may not be the latest.
 
*Overdue reports*. Find overdue reports in Circulation folder. There are templates capturing checkouts 
with due date within a selected time frame for all patrons or those without email address (phone list) 
or the due date is before a selected date. You may use these templates to set up your overdue reports 
capturing items which are at a certain number of days overdue.
 
*Circulation statistics reports*. These templates are in Circulation folder. The regular circulation 
statistics can be grouped by various criteria: patron's home library, profile and/or stat cat; items' 
owning library and/or shelving location. There are two sets of templates: one set limit the circulation 
period by selected dates kept in Circulation within time frame folder; the other selected month(s), in Monthly Circulation Stats folder. The latter are for generating monthly recurring reports.
 
Other circulation statistics related templates are:
 
* non-catalogued circulation count
* pre-catalogued circulation count
* pre-catalogued circulation count for items with dummy title prefix of "ILL:" (ILL statistics via pre-catalogued circulation)
* checkin count
* in-house use count for non-catalogued items
* in-house use count for catalogued items
* in-house use count per title

Other circulation related templates are:
 
* lost and paid item list
* lost with outstanding bills item list
* claimed returned item list
 
*Reports on collection*. These templates are in Collection folder. You will find templates counting items 
or titles of your whole collection or catalogued within the selected time period (new title/items statistics). 
The numbers are grouped by shelving location and/or circulation modifier.
 
Another group of templates in Collection folder are item/title lists for items meeting various criteria: 
having selected shelving location(s) and/or circulation modifier(s), copy stat cat, barcode prefix, call 
number prefix or within a call number range; or being catalogued (new title/item list), marked missing, 
lost or deleted within selected time period.
 
In this folder, you will also find templates listing pre-catalogued items and items with certain circulation 
history (items with fewer circulation count for weeding report or more circulation count for popular 
title/item report).
 
*Patron reports*. All patron reports are in Patrons folder. You may find templates counting patrons by 
profile group and/or patron stat cat, registered or expired/expiring within a selected time period, or 
with circulation history within a selected time period.
 
Another group of templates list selected information for patrons meeting some conditions such as: email list 
for all or those patrons having certain stat cat; names and barcode for patrons without circulation history 
within selected time frame; patrons born before a selected date (seniors list); patrons exceeding maximum 
fine limit.
 
Besides, there is a template that counts patron's OPAC logins and another that summarizes the answers to 
patron survey question(s).
 
*Reports on bibliographic information*. It is not easy to generate reports based on bibliographic 
information due to the bibliographic record structure. But a simple report that lists the values in a 
selected MARC tag and subfield for the whole collection is possible. And the bibliographic records can be 
limited by a selected value of a MARC tag and subfield. These templates are in Bibliographic Records folder.
 
*Bills and payments*. You can find the templates listing the details of various kinds of payments made 
in a selected time period, and a template listing bills with negative balance.
 
*Hold reports*. Holds related reports are in this folder, including reports for holds that have been long 
time outstanding (requested some time ago but not filled yet), cancelled, or have no eligible copies to be 
filled. There are other templates that count the total number of holds placed or fulfilled within a time 
span, and the hold count per title for popular titles.
 
*Inventory*. The two templates in Inventory folder list items based on whether the item showed up 
(being scanned on shelves or returned) in the library while the inventory was taken. The result of 
the Inventory - un-scanned items are the potential missing items.
 
*Library setting and policy related reports*. Find them in Library Configuration folder.
 
*Other folders*. If your library uses the Acquisitions Module, Serials or the Booking Module, you may find related 
templates in the relevant folders.
 
*Custom Templates folder*. If you open this folder, you will see a subfolder for your library federation 
with sub-subfolders for your library and other libraries within your library federation.
  
These folders are created when the Support Team creates or customizes templates for individual 
libraries. The templates go to these folders when there are similar templates in the standard folders 
already, or Coop support does not anticipate wide use of the templates. Coop support tries to 
limit the number of templates in each standard folder so that staff may find the target template easily.
 
Clone a template from Sitka_templates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The steps below assume you have already created at least one Templates folder.  If you have not done so, 
please see xref: _folders_[].
 
. Access the Reports interface from *Administration* -> *Reports*
. Under Shared Folders expand the Templates folder and the Sitka_templates subfolder.  To expand the 
folders click on the grey arrow or folder icon.  Do not click on the blue underlined hyperlink.
. Click on the Circulation (SITKA) subfolder.
. Select the template you wish to clone. In this example, we are cloning the Monthly Circulation 
by Shelving Location template.  From the dropdown menu choose Clone selected templates, then click Submit.  
.. By default Evergreen only displays the first 10 items in any folder. To view all content, 
change the Limit output setting from 10 to All.
. Choose the folder where you want to save the cloned template, then click Select Folder. Only template 
folders created with your account will be visible. If there are no folders to choose from please see 
Chapter 27, Folders.
. The cloned template opens in the template editor. From here you may modify the template by adding, 
removing, or editing fields and filters as described in Chapter 28, Creating Templates. Template Name 
and Description can also be edited. When satisfied with your changes, click Save.
. Click OK in the resulting confirmation window.
 
Modify a template
~~~~~~~~~~~~~~~~~

Once saved it is not possible to edit a template. To make changes, clone the template and change the clone.
 
To modify a template, repeat the above steps 1-6. You will see the template open on Template Creating screen. 
Click Displayed Fields you will see all the displayed fields. To remove one, highlight it and click 
Remove Selected Field. You may move a field up or down the list, which will affect the sorting of the 
result records. You may also change the column label or the transform of the field by using respective 
buttons. See Field Transforms section for more information.
 
[TIP]
=====
* Removing displayed fields usually does not affect the result set. But sometimes it does, esp. when the 
report displays the count of records by each group. Sometimes some fields may contain important information. 
Removing them may cause misunderstanding the results. Usually such fields are explained in the template 
Description. Be cautious when you delete such fields.
* If you are not clear where a displayed field is from, you may use the Source Browser to the right to display 
fields from the selected table only.
=====
 
To add a displayed field, go to the Sources to open the source table to find the field or follow the links 
to the appropriate table which contains the field you want to display. Click the text in the Sources to 
display fields in the table in Field Name pane. Click the arrow in front of the text to display the linked 
tables in the Sources pane.
 
Once find the field, select it in Field Name pane and the appropriate transform in Field Transform pane. 
Click Add Selected Fields.
 
The below screenshot shows how to add Precat Dummy Title field. Find Circulating Item table, which is linked 
from Circulation. Click it (text) to display its fields in Field Name. Select Precat Dummy Title, and then 
Raw Data in Field Transform.
 
CAUTION: You can not change the starting source table, but have to follow the links to tables in the Sources 
pane. Changing the starting table will remove all existing fields, meaning building a new template from scratch.
 
Select Base Filters or Aggregate Filters to add or remove filters. The steps are the same as adding or 
removing displayed fields. Be careful with filters as usually changing filter makes a difference in the 
result set.
 
Examples of using Sitka's templates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CAUTION: Please clone templates in Sitka_templates and set up your reports from your own copy. This is to avoid any 
potential impact that may be resulted from changing the orignal templates. The Support Team regularly 
maintains these templates. Deletion may happen. Deleting a template will delete all linked reports and 
output files.
 
Below are a few screenshots showing you how to set up the reports based on some templates in Sitka_templates. 
Some explanation is added in the boxes with light coloured background.
 
. Setting up a monthly recurring report by using template: Monthly Circulation by Shelving Location 
(updated to include item's owning library) in Circulation folder:
 
. Setting up a weekly recurring report by using template: Overdues Within Time Span - for Patrons without 
Email in Circulation folder:
 
. Setting up a one-time report by using template: Circulation Statistics by One Patron Stat Cat within 
timespan in Circulation folder:
 
. Setting up a report by using template: Items List by Shelving Location in Holdings folder:
 
. Setting up a report by using template: Weeding - Items with few circulations since a selected month 
in Holdings folder:







