Troubleshooting Report Templates
--------------------------------

(((Troubleshooting, Reporter)))
(((Reporter, Troubleshooting)))
(((Report Templates, Troubleshooting)))

If you run into difficulties creating or modifying a template you can https://bc.libraries.coop/support/[contact Co-op Support]
for assistance.  Please be aware that tickets for reports requests may take 1 to 2 weeks.

Before contacting Co-op Support please ensure the applicable template folder is 
xref:_sharing_folders[shared with your library] so Co-op Staff are able to view the template in question.

When contacting Co-op Support please include the following information:

* Username of the staff account where the template has been created
* Folder where the template has been created
* Name of the template in question
* Desired end result for the template (what do you want it to report on?)
* Specific display fields or filters you are having difficulties modifying or adding
* Links to your current report output from the template if relevant
