Course Reserves Administration
------------------------------

To enable the course materials module, go to Administration ->
Local Administration -> Library Settings Editor. Find the setting called
"Opt Org Unit into the Course Materials Module". Set it to True for the
org units that want to use the module.  You may add courses and materials
prior to enabling this setting.  However, they will not display in the
catalog until the setting is enabled.

There are additional library settings that apply to the Course Materials
Module:

* _Allow users to browse Courses by Instructor_: Some libraries may associate
many of their courses with their instructors.  Some may not associate any of
their courses with an instructor, or the instructor data may be inconsistent.
A _true_ value for this setting is appropriate for libraries that have
consistent instructor data and want to allow patrons to locate courses in
the OPAC via instructor name.
* _Bib source for brief records created in the course materials module_:
The course materials module will use this bib source for any new brief
bibliographic records made inside that module. A transcendant bib source is
likely preferable here, as it would allow an electronic resource to display
in the public catalog without adding any items or located URIs.

To use the course materials module effectively, staff will need a new
permission called _MANAGE_RESERVES_. In the default permission structure,
circulation administrators receive this permission.

Adding terms
~~~~~~~~~~~~

You may optionally keep track of your institutions terms or semesters.
To add a new term:

. Navigate to Administration -> Local Administration -> Course Reserves List.
. Open the Terms tab.
. Press the "New Term" button.
. Fill out the form and press the "Save" button.

Modifying course roles
~~~~~~~~~~~~~~~~~~~~~~

Evergreen users can be associated with courses in various roles.  For example,
one Evergreen user may be associated as the instructor of a course, while others
are associated as students in the course.

Course roles are shared across the entire Evergreen installation, rather than
being specific to a specific library.

To modify course roles:

. Navigate to Administration -> Local Administration -> Course Reserves List.
. Open the Course roles tab.
. When modifying course roles, be very careful about whether or not they are
_OPAC Viewable_.  Having an instructor role viewable in the OPAC could be very
beneficial, as it could enable students to locate their course using the name
of their instructor.  However, having a student role viewable in the OPAC could
be a violation of the students' privacy rights, as it would expose their course
registration to the general public.

Adding courses
~~~~~~~~~~~~~~

To add a course:

. Navigate to Administration -> Local Administration -> Course Reserves List.
. Press the "Create course" button.
. Fill out the characteristics of the course.  The course's number, name, and
owning library are required.  The section number is not.
. Once you have created a course, you can optionally associate it with the
terms (or semesters) that it is taught in.  Do this by clicking the "Terms
taught" link next to the course you created.  Press the New Course Term Map button
and select the Term you wish to associate.  You can associate as many or as
few terms as you wish to any course.

Adding materials to courses
---------------------------

You may attach several different types of materials to a course.

Attaching an item to a course
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

These procedures are intended if you already have an item with a barcode
in your catalog, and you wish to attach it to a course.

- Navigate to Administration -> Local Administration -> Course Reserves List
- Select an existing course.
- Choose Edit Selected from the Actions menu.
- Open the Course materials tab.
- Enter the barcode of an item you wish to attach to the course.
- You may optionally describe the relationship of the item to the course.  For
example, the item may be "required reading" or "optional listening".
- If necessary, you may temporarily change various characteristics of the item
while attaching it.  For example, if you are bringing a book from your typical
stacks to the reserves room, you may wish to change the book's shelving location,
circulation modifier, and call number.  The characteristics will remain in effect
until the item is detached from the course or the course is archived.
- Press the "Add material" button.


Attaching a brief record to a course
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

These procedures are intended if you wish to attach a resource to a course,
and the resource is not in your catalog.

- Navigate to Administration -> Local Administration -> Course Reserves List
- Select an existing course.
- Choose Edit Selected from the Actions menu.
- Open the Course materials tab.
- Open the "Associate brief record" tab.
- Fill out the metadata for the resource.
- You may optionally describe the relationship of the resource to the course.
- Press the "Add material" button.

After creating a brief record, it is represented as a bibliographic record in
your catalog, which catalogers may edit and enhance at any time.  When the resource
is detached from the course or the course is archived, the bibliographic record
will be automatically deleted.

Attaching a cataloged electronic resource to a course
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

These procedures are intended if you wish to attach a resource to a course,
and the resource is an electronic resource in your catalog.  An example of
this type of resource is a library-licensed ebook that is used as a course
textbook.

- In the staff catalog, find the electronic resource that you would like to
add. In the record summary, note the Database ID.
- Navigate to Administration -> Local Administration -> Course Reserves List
- Select an existing course.
- Choose Edit Selected from the Actions menu.
- Open the Course materials tab.
- Open the "Associate electronic resource from catalog" tab.
- Enter the resource's bibliographic ID.
- You may optionally describe the relationship of the resource to the course.
- Press the "Add material" button.

Unlike brief records, detaching this resource from the course or archiving the
course will not delete the bibliographic record.
