[[sitkas-evergreen-support]]
Sitka's Evergreen Support
-------------------------

The Co-op Support team strives to respond to new requests within 24 hours, excluding weekends. To manage
requests (also referred to as tickets) the Support team uses ticket tracking software called
*Request Tracker (RT)*.

How to Contact Support
~~~~~~~~~~~~~~~~~~~~~~

There are four ways to contact Co-op Support for regular Evergreen support:

. *Request Tracker Interface*. Submit and track requests with RT Self Service. After
logging in you may use the form to create new tickets, track the progress of open tickets, or
review issues that have been resolved.  More information can be found in
xref:_rt_self_service[].

. *Email*. Send questions to the support email address. Requests submitted by email generate RT tickets and can also be viewed online by logging in to RT Self Service.

. *Online Contact Form*. Send questions to Co-op Support through the
https://bc.libraries.coop/support/[contact form] on the BC Libraries Cooperative website. Requests
submitted through the contact form generate RT tickets and can also be viewed online by logging in to
RT Self Service.

. *Phone*. Telephone support is available *9:00 AM to 4:00 PM Pacific Time, Monday to Friday*.  Call our toll free number during regular
hours to speak with support staff or leave a message. To protect our staff we do not accept anonymous calls so please ensure your caller
ID is not blocked.

The Co-op Support toll free number can be found on the
https://bc.libraries.coop/support/sitka/[Sitka Support] page. This information is also given to libraries
during migration.

Emergency Support
^^^^^^^^^^^^^^^^^

Emergency support is available outside of regular support hours.  If you are unable to connect to 
the Evergreen server, your LibPress site is down, or patron authentication via SIP or PatronAPI is down call our
toll free support number and select option 9 to connect to an on-call tech.

[[support-guidelines]]
Guidelines for Support Requests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

https://youtu.be/QIhx6KTXERk[*Submitting Support Tickets (5:47)*]

Thorough and consistent reporting makes it easier for Co-op Support to respond to your requests.

* *Report problems as they occur*. Prompt reporting may help us catch a problem before it affects other patrons, respond quickly to issues that impact multiple libraries, or save you time if there is an easy solution. Please report issues as soon as is convenient.

* *One issue per request*. Please submit one issue at a time. Emails generate tickets in RT which are assigned to support team members. Reporting each question separately helps us assign, classify, and prioritize tickets more efficiently.

* *Contact information*. We strive to offer friendly, personalized service. Please include your name, your library, and use an email address where we can reach you directly.

* *Descriptive subject*. To make tickets easier to identify in RT please provide as descriptive a subject as possible.
** Example of a descriptive subject line: Circ+Full Cat login unable to edit item record
** Example of a non-descriptive subject line: Editing question

* *What, where, when, how?* Be specific about what you were doing in Evergreen, what results you obtained versus what you expected, and the steps required to reproduce the problem. If you cannot reproduce the problem exactly please describe the circumstances in which it occurred and the symptoms observed, including relevant patron and item barcodes.

* *Include error messages*. If the problem caused any OPAC or staff client error messages please 
copy and paste error text or attach screenshots when possible. See xref:_submitting_files_to_support[] for guidelines.

* *Include example barcodes and IDs*. A problem in circulation? Make sure you include the patron and/or item barcodes that were in use when the problem occurred. Cataloguing issues? Make sure you include the item barcode and/or the record ISBN/ISSN or record ID where the problem occurred.

* *Do NOT send passwords*.  Co-op Support will never ask for patron or staff passwords.

* *Include report output URLs*. If you're reporting an issue or question related to a specific report 
you've run make sure you include the link to the report output so that Support view it.

* *Troubleshooting*. Spare yourself a boring or obvious email from the Support Team: tell us what steps you have already taken to try and resolve the problem.

Submitting Files to Support
^^^^^^^^^^^^^^^^^^^^^^^^^^^
When submitting files to Co-op Support please follow the guidelines below:

* Submit images as a .jpg or .png.
** The best file formats in which to save screenshots are .png and .jpg. These files are easily accessed by Sitka Support and are unlikely to contain viruses.
* Submit plain text files (.txt) for text changes to things such as email notification wording.
* Do not submit .doc or .docx unless absolutely necessary.
** Files saved as .doc or.docx require additional software to open them and have a higher potential for carrying viruses.

RT Self Service
~~~~~~~~~~~~~~~
Each library has one account to access RT. Under this account staff are able to see all the tickets associated with their library. Not sure what the username and password is for your library's account? Contact Co-op Support to find out.

Access RT Self Service
^^^^^^^^^^^^^^^^^^^^^^

You can login on the RT website https://support.libraries.coop/rt/

The Self Service home page displays current tickets submitted by email or in RT. To re-open a closed ticket simply add a new reply. This will change the status to open and alert Co-op Support that more attention is required.
