Sitka and Evergreen Resources
-----------------------------

*Sitka Policy*

* http://docs.libraries.coop/policy/[Sitka's Evergreen Policy & Best Practices Manual] contains policy and best-practice documents 
supporting Sitka's consortial installation of the Evergreen ILS.

*Websites*

* The BC Libraries Cooperative website (https://bc.libraries.coop/support/sitka/) provides information about 
the implementation of Evergreen in BC, Manitoba, and Ontario including  Sitka documentation, 
and Sitka policy and governance documents.

* See the Evergreen site (http://evergreen-ils.org/) for information about Evergreen for all audiences, 
not specific to Sitka. Includes links to the Evergreen blog, the software development roadmap, 
and general documentation.

*Listservs*

* Join the Sitka Group on the BC Libraries Cooperative website where current member libraries discuss 
Sitka's implementation of Evergreen.
** Library directors and managers can https://bc.libraries.coop/support/[contact Co-op Support]
 to request BC Libraries Cooperative accounts for their staff.

[NOTE]
======
Any library specific questions that include patron information should be directed to Co-op Support.
======

* Evergreen Mailing Lists http://evergreen-ils.org/communicate/mailing-lists/
** Multiple lists for discussions of Evergreen inclding general, acquisitions, cataloguing, and circulation.
** Messages sent to the General, Developer, and DIG Evergreen lists are searchable 
at http://georgialibraries.markmail.org/search/

*Sitka Community Documentation*

We encourage Sitka sites to share locally produced Evergreen documentation with the wider Sitka 
community. If you have any guides, tutorials, or tip sheets to share please contact Co-op Support.
