New Features in Evergreen Version 3.9
-------------------------------------

https://www.youtube.com/playlist?list=PLdwlgwBNnH4r5hUb0EkOYmSv4kLv5QaL7[*New Features in Sitka's Evergreen 3.9 Playlist*]

[[new-features-staff-client]]
Staff Client
~~~~~~~~~~~~

* Actions menu option allows you to remove actions you don't use from the Actions menu in certain interfaces.
* Setting to turn on full library names in newer interfaces.
** link:https://youtu.be/pgDPRt3J-MM[*Sitka Snippet Video - Turning On Full Library Names (1:19)*]

[[new-features-circulation]]
Circulation
~~~~~~~~~~~

* Patron notes, alerts, and messages are now managed through a single interface.
* Password reset link button in patron Edit to enable staff to initiate a password reset for a patron.
** link:https://youtu.be/WNQwt2zXxOY[*Sitka Snippet Video - Resetting a Forgotten Password (2:10)*]
* New patron photo URL field added to patron account.  Access to this feature is not available by default.  
Please contact https://bc.libraries.coop/support/[Co-op Support] for more information.
* New look for holds pull list
** link:https://youtu.be/CYmk2mwgI5E[*Sitka Training Video - Pull List for Hold Requests (2:59)*]
* New look for the triggered events log

[[new-features-cataloguing]]
Cataloguing
~~~~~~~~~~~

* New and improved Holdings Editor.
** https://youtu.be/7WBAJ1Unz_M [*Sitka Training Video - Holdings Editor (14:12)*]

[[new-features-staff-catalogue]]
Staff Catalogue
~~~~~~~~~~~~~~~

https://youtu.be/PGiYGKJuOnU[*Sitka Training Video - Search the Catalogue (5:56)*]

* More details button in search results that reveals either the grid with item information and/or URLs.
* Call number now displays in the brief details in the search results.  This is the call number of the first item
listed in the grid with item information.
* Holding counts display in the search results for the preferred library.
* Preferred library holdings display on top in the grid with item information.

[[new-features-public-catalogue]]
Public Catalogue
~~~~~~~~~~~~~~~~

* Re-designed public catalogue with a new look
* Option for patrons to select their locale which determines the language their email notifications are sent in

[[new-features-course-reserves]]
Course Reserves
~~~~~~~~~~~~~~~

* New course reserves module within Evergreen which replaces the existing 3rd party course reserves module.

[[new-features-patron-notifications]]
Patron Notifications
~~~~~~~~~~~~~~~~~~~~

* Email notifications are now available in French to patrons who set their locale to French.  Libraries that wish the French notifications to match
their customized English notifications must provide translations to Co-op Support.

[[new-features-administration]]
Administration
~~~~~~~~~~~~~~

* Shelving Location Order interface enables libraries to re-order their shelving locations for
their pull list for hold requests.
** https://youtu.be/hjcLkDG2IFM[*Sitka Snippet Video - Shelving Location Order (1:22)*]
