New in Evergreen Version 3.1
----------------------------

Circulation
~~~~~~~~~~~

Email Checkout Receipts
^^^^^^^^^^^^^^^^^^^^^^^

This feature allows patrons to receive checkout receipts through email at the circulation desk and in the Evergreen self-checkout interface. Patrons need to opt in to receive email receipts by default and must have an email address associated with their account. Opt in can be staff mediated at the time of account creation or in existing accounts. Patrons can also opt in directly in their OPAC account or through patron self-registration. This feature does not affect the behavior of checkouts from SIP2 devices.

Patron Buckets
^^^^^^^^^^^^^^

Patron Buckets allow staff to batch delete and make batch modifications to user accounts in Evergreen.

Cataloguing
~~~~~~~~~~~

Copy Alerts
^^^^^^^^^^^

Copy Alerts allows library staff to add customized alert messages to copies. The copy alerts will appear when a specific event takes place, such as when the copy is checked in, checked out, or renewed.

Serials
~~~~~~~

Web Client Serials Module
^^^^^^^^^^^^^^^^^^^^^^^^^
The web client serials module has a new unified interface that combines ideas from both the serial control view and alternate serials control view from the old staff client.

In addition to carrying over functionality that was available in the old staff client, several new features are included:

* A more streamlined interface for managing subscriptions, distributions, and streams
* A new *Serials Administration* page where prediction pattern and serial copy templates can be managed.
* Prediction pattern codes can be saved as templates.
* The new serials interfaces can be accessed from the record details page via a Serials drop-down button.
