New Features in Evergreen Version 3.5
-------------------------------------

https://www.youtube.com/playlist?list=PLdwlgwBNnH4qvEzhSkKbhnH6OcQzsHSNm[*Sitka's Evergreen 3.5 - New Features Playlist*]

Web Staff Client (Web Client)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* Hatch - Workstation name is now stored in Hatch.

* Hatch - A new stock printer called the Hatch File Writer translates print content into text and writes the data to a file on the PC in the Hatch profile directory.

Circulation
~~~~~~~~~~~

* Circulation staff can mark an item Discard/Weed on checkin, item status, renew, and other patron and hold screens.

* Checked out items can now be marked as Missing, as well as Discard/Weed, and be automatically checked in before having their status changed to Missing, or Discard/Weed. If staff choose not to check them in, their status is not changed.

* Library Links in Billing Details Screen -The Full Details view now includes links to information about the billing and owning libraries. This can be useful in situations where circulation staff are troubleshooting a bill and would like to quickly find contact information for the billing or owning library

* Update Hold Notification Information – Evergreen now has the ability to update existing holds if a patron or a staff member changes certain notification preferences or contact information. Evergreen will detect these changes and prompt the staff user or patron user if they want to update existing holds with the new contact information and/or notification preferences.

Cataloguing
~~~~~~~~~~~

* The full MARC Editor is now implemented in Angular (Available in the Experimental Staff Catalogue)

* Staff Catalogue Basket Export Option (Available in the Experimental Staff Catalogue)


Catalogue/Public Catalogue
~~~~~~~~~~~~~~~~~~~~~~~~~~

* Update Hold Notification Information – The public catalogue and staff client now have the ability to update existing holds if a patron or a staff member changes certain notification preferences or contact information. Evergreen will detect these changes and prompt the staff user or patron user  if they want to update existing holds with the new contact information and/or notification preferences.


Library Settings
~~~~~~~~~~~~~~~~

* GUI: Enable Experimental Angular Staff Catalog - turns on the Experimental Staff Catalogue


Bug Fixes
~~~~~~~~~

* Patron's hold notification preferences are now saved correctly, with no need to manually re-set preferences when saving other edits to the patron record.

* Date displays correctly in the check out screen’s due date box.

* Choose specific due date for check out no longer allows due dates in the past.

* Evergreen now asks users to confirm that they want to delete items that are in non-ideal statuses, like Checked Out.

* The MARC batch import/export interface allows users to view and edit the incoming MARC records while inspecting an imported queue.

* Notify by Email column on the Holds Shelf now populates with yes/no as expected.

* On the Holds Shelf, only holds that can be cleared shows as clearable holds.
