[[cat-copy-bucket]]
Copy Bucket
-----------

https://www.youtube.com/watch?v=4W-zw-jieos[Sitka Snippet Video - Copy Buckets (3:48)]

Buckets is the name for a batch change functionality in Evergreen, or for a function that groups records in one place.  Batch changes allow you to group together many records and enact changes on them all at once, instead of individually editing them. Buckets can also be used to create pull lists. Buckets allow you to track and work with your materials in arbitrary ways and more easily collaborate with others.

This chapter will demonstrate a variety of ways in which you can manage your copies with Buckets.

Currently there are copy and title record buckets. You may work on copy records with Copy Buckets and MARC records with Record Buckets.

Some possible uses for buckets are batch editing items, deleting items, and grouping like items temporarily to change their status or to create bibliographies and pull lists. While you can batch edit records a variety of ways in Evergreen, using common Windows functions such as select all and edit, buckets are useful for keeping records together over a period of time. For example, if you scan 20 items into the Item Status screen you can batch edit or delete from there by selecting all, but you have to enact those changes right then while records are all together on the screen. By utilizing Evergreen's bucket functionality, you can create a bucket and add records to that bucket, and they stay there until you are ready to work with them, whether that be immediately or days later. Adding items to a bucket is like creating and saving a query. The record being in a bucket does not affect normal library functions such as circulation, as being in a bucket is not a status.

Buckets can be shared or private, and are associated with a login account.

[TIP]
=====
Deleted records are not automatically removed from buckets. It is recommended that you always display Deleted? field in Bucket View.

When a bucket is retrieved, all information about the records in it is transferred to the workstation. It consumes the computer's resources. It is recommended that a copy bucket contain no more than a few hundred records.
=====

Creating Copy Buckets
~~~~~~~~~~~~~~~~~~~~~~



Adding/Removing Copy Records to/from a Bucket
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Working with Copies in a Bucket
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Retrieving Shared Buckets
~~~~~~~~~~~~~~~~~~~~~~~~~