Searching the Database for Cataloguing Purposes
-----------------------------------------------

https://youtu.be/u86TxsX3CY0[Sitka Training Video - Search the Catalogue (4:35)]

It is critical to search the database before adding titles, volumes, or copies. Good practice is to assume 
the item you are adding already exists, and to do an exhaustive search for the item before cataloguing it. 
By doing so, you will discover whether you need to add your item to an existing title record, or if you need 
to import or create a new title record. It is very important that you scope your cataloguing searches to the 
entire Sitka database, either at the time of each search or via Workstation or My Account preferences.

You can set workstation search preferences  to configure default search location and preferred search library, 
and you can choose to have Numeric Search or MARC Expert search be the default advanced search view. These 
workstation preferences override account login preferences set in My Account. For cataloguing workstations 
it is recommended that the Default Search Library be set to Sitka. This will ensure staff using those 
workstations are always searching all of Sitka.


It is critical to search the database before adding titles, volumes, or copies. Good practice is to assume the item you are adding already exists,
and to do an exhaustive search for the item before cataloguing it. By doing so, you will discover whether you need to add your item to an existing
title record, or if you need to import or create a new title record. It is very important that you scope your cataloguing searches to the entire
Sitka database.


include::search/catalogue-preferences.adoc[Catalogue Preferences]

include::search/keyword-search.adoc[Keyword Search]

include::search/numeric-search.adoc[Numeric Search]

include::search/marc-search.adoc[MARC Search]

include::search/search-results.adoc[Viewing Search Results for Cataloguing Purposes]
