[#cat-search-for-cataloguing]
Searching the Database for Cataloguing Purposes
-----------------------------------------------
https://www.youtube.com/watch?v=lIEPR47y06E[Sitka Training Video - Search the Catalogue (5:16)]

It is critical to search the database before adding titles, volumes, or copies. Good practice is to assume the item you are adding already exists, and to do an exhaustive search for the item before cataloguing it. By doing so, you will discover whether you need to add your item to an existing title record, or if you need to import or create a new title record. It is very important that you scope your cataloguing searches to the entire Sitka database, either at the time of each search or via Workstation or My Account preferences.

You can set workstation search preferences to configure default search location and preferred search library and you can choose to have Numeric Search or MARC Expert search be the default advanced search view. These workstation preferences override account login preferences set in My Account. For cataloguing workstations it is recommended that the Default Search Library be set to Sitka. This will ensure staff using those workstations are always searching all of Sitka.

include::search/advanced-numeric.adoc[Advanced/Numeric Search]

include::search/marc-expert.adoc[MARC Expert Search]
