Batch Loading Bibliographic Records
-----------------------------------

https://youtu.be/2ZtDXTqaXcE[*Sitka Training Video - Uploading MARC Records via MARC Batch 
Import (3:49)*]

Libraries can load MARC record files supplied by vendors into Evergreen.  What is included in the file can vary from
vendor to vendor and depend on the stage of the cataloguing process. 

* Brief Records With No Holdings Information
* Brief Records With Holdings Information To Create Items
* Full Records With No Holdings Information
* Full Records With Holdings Information To Create Items
* Full Records With Holdings Information To Update Existing Items
* Full Records For Electronic Resources With 856 Fields

Cataloguers should always follow the policy for batch loading records which can be found in the section  
http://docs.libraries.coop/policy/_batch_loading_bibliographic_records.html[Batch Loading 
Bibliographic Records] in Sitka's Evergreen Policy & Best Practices Manual.

Importing records involves two steps:

. All records in the file are first xref:_uploading_marc_record_files[uploaded to the server]
 and kept outside the catalogue as a queue.
. Cataloguers view the records in the queue and then 
xref:_importing_marc_records[import them into the Evergreen catalogue].

include::add-marc-batch/marc-import-fields.adoc[MARC Importer]

include::add-marc-batch/marc-import-templates.adoc[Import Templates]

include::add-marc-batch/marc-upload-MARC-file.adoc[Uploading MARC Record Files]

include::add-marc-batch/marc-import-MARC-records.adoc[Importing MARC Records]

include::add-marc-batch/marc-manage-queue.adoc[Managing Import Queues]


