[[edit-marc]]
Maintaining Bibliographic records
---------------------------------

The appropriate title information displayed on OPAC relies on correct MARC coding. For example, format icons for text, moving pictures and sound rely on  MARC coding in the leader, and 007 and 008 fields, as do OPAC search filters, such as publication date, item type, or target audience. Bibliographic records matching and de-duplicating also rely on correct MARC coding and consistency in use of and contents in particular MARC tags. The ability to edit and manage MARC records is very important to maintaining database integrity.

Evergreen allows you to edit MARC tags, sub-fields, and indicators, as well as an easy entry box to edit parts of the leader and 008 field on a built-in form called MARC Editor. Besides, it also provides a text based editor, which allows you to easily add or remove tags, and/or edit the fields. But you need to pay close attention to the position of the tags, indicators and the spacing required to preserve the record structure.

include::edit-marc/edit-marc.adoc[Editing MARC Records]

include::edit-marc/edit-leader.adoc[Editing MARC Record Leader and Fixed Fields]

include::edit-marc/format-filter.adoc[Format Filters and Format Icons]

include::edit-marc/merge-bib.adoc[Merging Bibliographic Records]

include::edit-marc/delete-bib.adoc[Deleting Bibliographic Records]

include::edit-marc/export-bib.adoc[Exporting Bibliographic Records]

