Bibliographic Records in the Experimental Catalogue
---------------------------------------------------

The appropriate title information displayed on the OPAC relies on correct MARC coding. For example, 
format icons for text, moving pictures, and sound, rely on  MARC coding in the leader, 007, and 008 tags, 
as do OPAC search filters, such as publication date, item type, or target audience. Bibliographic record 
matching and de-duplicating also relies on correct MARC coding and consistency in use of, and contents in, 
particular MARC tags. The ability to edit and manage MARC records is very important to maintaining database 
integrity.

Evergreen allows you to edit MARC tags, sub-fields, and indicators, as well as an easy entry box to edit 
parts of the leader and 008 field on a built-in form called the MARC Editor. It also provides a text based 
editor, which allows you to easily add or remove tags, and/or edit the fields. You need to pay close attention 
to the position of the tags, indicators, and spacing required to preserve the record structure.

include::marc-edit/catnew-edit-marc.adoc[]

include::marc-edit/catnew-search-filter.adoc[]

include::marc-edit/catnew-edit-leader.adoc[]

include::marc-edit/catnew-edit-007.adoc[]


////
    Merging Bibliographic Records
    Deleting Bibliographic Records
    Exporting Bibliographic Records
////