Evergreen System Requirements
-----------------------------

Evergreen runs smoothly on most modern computers with a good internet connection. To ensure your system is ready for migration here are a few tips and minimum requirements.

*Internet Connectivity*

Most internet traffic uses moments of brief connectivity rather than a persistent connection so it is not unusual when experiencing connectivity issues to notice it in the Evergreen staff client.

Evergreen will work down to a 3Mbps connection, but the performance will get progressively worse the lower the connection speed gets. While Evergreen will be functionally usable at 3Mbps it may of limited use at lower speeds. Ideally it runs at 12Mbps.

.Recommended Internet Connection Speeds
[options="header"]
|====
| Category |	Downstream |	Upstream |	Latency (to Sitka)
| Bare Minimum To Function |	3Mbps |	786Kbps |	less than 200ms
| Adequate |	6Mbps |	1Mbps |	less than 125ms
| Ideal |	12Mbps |	2Mbpbs |	less than 75ms
|====

Most of the bandwidth usage in a library is not from Evergreen, but from other usage of the internet by both staff and patrons. When staff workstations share an ISP connection with public workstations libraries ideally should have at least 1.5-2x more down/upstream capacity than what is recommended in the table above.

*Staff Terminals*

Staff terminals connect to the central server using the Evergreen web client, currently supported 
by BC Libraries Cooperative in the Chrome browser only .

* Operating System
** Windows 10 or 11.  Users may need to manage privacy settings based on best practice in Windows community 
or on advice of your IT department or vendor.
** Mac OS X 13.7 or higher.
** Linux
* Chrome - updated to the newest available version.  Libraries should not run Chrome versions 122 or lower.
* a reliable high speed internet connection
* 512Mb of RAM

[NOTE]
======
The Evergreen staff client will not display properly on computers running older unsupported operating systems 
and using older unsupported versions of Chrome.

We strongly recommend that libraries ensure their staff computers are always running a supported operating system.
======

*OPAC Terminals*

There is no stand-alone public catalogue client for Evergreen. Patrons search the catalogue 
using a web browser. Each public catalogue terminal will require at minimum:

* a reliable high speed internet connection
* a web browser, e.g. Firefox, Chrome or Edge


To limit your OPAC terminals to catalogue searches local configuration will be required. 

*Barcode Scanners*

Evergreen will work with virtually any barcode scanner - if it worked with your legacy system it should work on Evergreen.

*Printers*

Evergreen can use most desktop or roll printers configured for your terminal to print receipts, 
check-out slips, holds lists, spine labels, etc. 
