Evergreen System Requirements
-----------------------------


Evergreen runs smoothly on most modern computers with a good internet connection. To ensure your system is ready for migration here are a few tips and minimum requirements.

*Internet Connectivity*


Most internet traffic uses moments of brief connectivity rather than a persistent connection so it is not unusual when experiencing connectivity issues to notice it in the Evergreen staff client.

Evergreen will work down to a 3Mbps connection, but the performance will get progressively worse the lower the connection speed gets. While Evergreen will be functionally usable at 3Mbps it may of limited use at lower speeds. Ideally it runs at 12Mbps.


Most of the bandwidth usage in a library is not from Evergreen, but from other usage of the internet by both staff and patrons. When staff workstations share an ISP connection with public workstations libraries ideally should have at least 1.5-2x more down/upstream capacity than what is recommended in the table above.

*Staff Terminals*

Staff terminals connect to the central database using the Evergreen web client, currently only supported by BC Libraries Cooperative in Chrome.

* Windows 10, 8, 7, or Vista operating system. Win 10 users may need to manage Win 10 privacy settings based on best practice in Windows community or on advice of your IT department or vendor.

* Mac OS X operating system.
* Linux operating system.
* a reliable high speed internet connection
* 512Mb of RAM

*OPAC Terminals*

There is no stand-alone OPAC client for Evergreen. Patrons search the catalogue using a web browser. Each OPAC terminal will require at minimum:

* a reliable high speed internet connection
* a web browser, e.g. Firefox, Chrome or Internet Explorer

NOTE: The OPAC will not work in Internet Explorer on computers running Windows XP. Co-op Support recommends you update your operating system or use Firefox or Chrome.

To limit your OPAC terminals to catalogue searches local configuration will be required. Please see Managing Internet OPAC Stations for more information.

*Barcode Scanners*

Evergreen will work with virtually any barcode scanner - if it worked with your legacy system it should work on Evergreen.

*Printers*

Evergreen can use most desktop printers configured for your terminal to print receipts, check-out slips, holds lists, etc. The exception is spine label printing, which requires roll printers. Evergreen currently formats spine labels for output to a label roll printer. If you do not have a roll printer manual formatting may be required.

NOTE: Evergreen might not print correctly to receipt printers using the Windows XP Generic/Text Only printer driver. Please use a printer-specific driver instead.
