Server Administration
---------------------

Most options under the Server Administration menu are global Sitka settings that cannot be changed locally. The exception inlcudes the call number prefix/suffix, and the  Organizational Units submenu, which allows Local System Administrators to edit library contact information, hours of operation, and addresses.

There is some view-only information that is useful under Server Administration, in particular the list of Copy Statuses.

Call Number Prefix and Suffix
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CAUTION: Call Number Prefix/Suffix created here are different from Label Prefix/Suffix created on Copy Location Editor. The former are displayed as part of call number in OPAC, while the latter are on printed labels only.

include::serveradmin/admin-org-unit.adoc[]

Organizational Units
~~~~~~~~~~~~~~~~~~~~~



Copy Status
~~~~~~~~~~~

This table below describes the copy statuses with Sitka's property settings.


[option="header"]
|=====
| Copy Status | Definition | Holdable | OPAC Viewable | Sets copy active | Is Available?
| Available	| Item is on the shelf	| Yes | Yes | Yes | Yes
| Bindery | Sent to be rebound | No| Yes| No| No
| Canceled Transit	| A transit for the item was aborted | Yes	| Yes	| No	| No
| Cataloguing	| Item is being catalogued or in cataloguing department	| Yes	| Yes	| Yes	| No
| Checked out	| Item is on loan	| Yes	| Yes	| Yes	| No
| Claimed Returned	| Patron reports item has been returned. (Libraries develop own procedure for deciding when to make an item Claimed Return)	| No	| Yes	| Yes	| No
| Cleaning	| Item is being cleaned (ie. DVDs and CDs)	| Yes	| Yes	| Yes	| No
| Damaged	| Damaged and may not circulate again	| No	| Yes	| Yes	| No
| Discard/Weed	| Item is no longer in collection, it has been weeded or discarded	| No	| No	| Yes	| No
| ILL	| Not currently used in Sitka.	| No	|No	| Yes	| No
| In process	| Item is being processed and will soon be available	|Yes	|Yes	| No	| No
| In transit	| Item is travelling between libraries and remains in the In Transit status until checked in	| Yes	| Yes	| Yes	| No
| Long Overdue	| Not currently used in Sitka.	| No	| No	| No	| No
| Lost	| Declared lost by patron or library (either manually or automatically) |	No	| Yes	| Yes	| No
| Lost and Paid	| Item was declared lost by patron or staff and has now been paid for.	| No	| Yes	| Yes	| No
| Mending	| Item is being repaired	| Yes	| Yes	| Yes	| No
| Missing	| Item cannot be found	| No	| Yes	| Yes	| No
| On display	| Item is on display and is not in its usual shelving location	| Yes	| Yes	| Yes	| Yes
| On holds shelf	| Item is awaiting pick-up by patron. Item is usually on a "holds shelf" within the library	| Yes	| Yes	| Yes	| No
| On order	| Item has been ordered but not yet received from a vendor	| Yes	| Yes	| No	| No
| On reservation shelf	| Used with room/booking module. When an item has been booked/reserved, it is placed in a unique location, ready for pick-up	| No	| Yes	| Yes	| No
| Onsite consultation	| Item is available for use on-site and possibly needs to be requested through staff. This is not intended for normal reference materials.	| No	| Yes	| Yes	| Yes
| Reserves	| In reserves collection	| No	| Yes	| Yes	| Yes
| Reshelving	| Item has been returned but not yet shelved. Status automatically changes to Available after 24 hours	| Yes	| Yes	| Yes	| Yes
| Storage	| On-site or off-site storage	| Yes	| Yes	| Yes	| No
| Temporarily Unavailable	| Not available for patrons to borrow but will become available at a later date	| No	| No	| Yes	| No
|=====

[TIP]
=====

. If the *Sets copy active* is set to NO, an item created with this status will not have the *Active Date* field filled. The date will be filled later when the item achieves a status with *Sets copy active* is set to YES.

. If Is Available? is set to YES, items with that status will appear in search results when the *Limit to Available* checkbox is checked and can be checked out without needing to be first checked in or have any prompts regarding unavailable status appearing.
====


Hard Due Date
~~~~~~~~~~~~~

One or more hard due date(s) can be set up for a library to force the circulation due on selected date(s). The hard due date is used in the circulation policy based on patron profile and/or item circulation modifier. It may be used to extend or shortern the regular loan duration. For example, it may be used to grant faculty members term loan by an Always Use? TRUE hard due date, or to force all students to return their items by the end of the term by an Always Use? FALSE hard due date, which takes effect when the regular due date falls after the hard due date. Please contact Sitka Support if you wish to use hard due date.

