[[admin-notice]]
Circulation, Hold, and Patron Account Notices
---------------------------------------------

Libraries can opt into a number of automated patron notifications.  These notifications are set up by 
Co-op Support.  If you are unsure what notifications your library has set up, please contact 
xref:https://bc.libraries.coop/support/[Co-op Support].

Notifications are sent in three ways, depending on the notification:

* Email - sent directly to the patron
* SMS Text Message - sent directly to the patron
* Mail - sent to the library as a PDF to be printed and mailed out 

Email Notifications
^^^^^^^^^^^^^^^^^^^

When sending out emails the BC Libraries Cooperative needs to follow all of the best practices and conventions
in order to avoid our emails being marked as spam and to have the best chance of the emails being delivered
successfully to your patrons.  One of the important things we do is ensure that any emails sent 
from our servers have a _From_ address with a domain that can be verified as coming from our servers.  This 
means that all emails sent by Evergreen will come from noreply-YOURLIBRARYCODE@catalogue.libraries.coop. How
this displays to your patrons will depend on their email client.

To discourage patrons from responding to these automated
notifications most of them start with _This is an automated message.  Please do not reply to this email._

In the email notification templates the _Reply to_ address is set to use the email address set for your library
in the library setting _Sending email address for patron notices_.  This ensures that if patrons do reply those
replies are directed to the email of your choice. Bounced emails are also directed to this email address and we 
encourage staff to xref:_invalidating_an_email_address[invalidate any email addresses] that bounce
to help keep us from being blacklisted by email providers.  

Email notifications from Sitka's Evergreen are not spam and should not be marked as spam by either patrons 
or staff.  If patrons do not wish to receive them they can opt out of receiving overdue and courtesy notice 
emails through the xref:_notification_preferences[Notification Preferences] in _My Account_.

Checking for Notifications
^^^^^^^^^^^^^^^^^^^^^^^^^^
(((Patron Notifications, Action Triggers)))
(((Triggered Events)))

Evergreen keeps a record of courtesy, overdue, and hold notifications sent out via email and SMS text 
message.  You can check to see whether or not a notification was generated.

These records are kept for 3 to 6 months, depending on the type of notification.

Evergreen sends various email and SMS (text) messages to patrons via *Action Triggers*.  Triggered events are viewable on the staff client in patron or item records.

. To view notifications in the patron account, select *Other → Triggered Events/Notifications*.
. Completed pre-due and overdue notifications are displayed by default. You can change the filters for *Core Type* or *Event State*, on the right, to view any or all notifications.
. To re-send a completed notice, select the notice, and click *Reset Selected Event* at top right of screen.
. To cancel a pending notice, select the notice, and click *Cancel Selected Event* at top right of screen.

[NOTE]
======
Action Triggers are used for, but not limited to, pre-due, overdue, and hold notification generation. You may see other triggered events in a patron or item record, but not all events generate notices. Events with status of Invalid or Error encountered problems during the process. No notices were generated for such events.
Pending and some statuses other than complete, error, or invalid, may last for a short period of time while the event is being processed.
======

Courtesy Notifications
~~~~~~~~~~~~~~~~~~~~~~

Courtesy notifications are generated and sent via email and/or SMS text message ahead of an item being due.  
If a library has both email and SMS text message courtesy notifications enabled patrons will received both.

[CAUTION]
=========
If the due date is extended via *Edit Due Date* after the courtesy notification is sent out, no 
additional courtesy notification will be generated. Staff are encouraged to use the *Renew* or 
*Renew with Specific Due Date* functions instead to ensure additional notifications are be generated in 
due course.
=========


Email Courtesy Notifications
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Courtesy notices are generated and sent via email to patrons before an item is due. The standard interval
is 3 days ahead of the due date but this can be customized.  Only patrons with email addresses in their 
patron account will receive email courtesy notifications.

To customize the wording or the interval of the notification please contact 
xref:https://bc.libraries.coop/support/[Co-op Support].


SMS Text Message Courtesy Notifications
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The SMS text message courtesy template is shared by all Sitka libraries and cannot be customized.

Libraries must opt in to have these notifications turned on. Please contact 
xref:https://bc.libraries.coop/support/[Co-op Support] to opt in.

Library courtesy notifications are generated and sent via SMS text message to patrons 3 days before 
an item is due. Patrons must have a default Default SMS/Text Number and Default SMS Carrier
 saved in their patron account to receive these notifications. See xref:_patron_account_fields[] for more
 information on these fields.

[CAUTION]
=========
The process that generates courtesy notices runs early in the morning.  SMS text messages are sent around 
*2:00am* PT. 
=========


Circulation Overdue Notices
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Overdue notices can be delivered via email, paper or phone.


Email Overdue Notice
^^^^^^^^^^^^^^^^^^^^

The server sends overdue emails to patrons once a day, after hours, when the fines generator runs. The emails are generated when an item is 7 days, and then 14 days overdue (this is a global Sitka setting).

These emails are not spam, and should not be marked as spam by either patrons or staff.

The overdue email notice templates can be customized at the federation or library level. Please contact Co-op Support for customization.

Paper Overdue Notice
^^^^^^^^^^^^^^^^^^^^

Evergreen generates a PDF file of overdue notices and emails the file to you to be printed and distributed to patrons. These notices are created and sent daily.

An empty PDF file means that there is no notice for the day due to no item filling in the overdue category. You will still receive the empty file. If you are not receiving daily PDF files please contact Co-op Support.

To set up paper overdues you need to provide Co-op Support with the following information:

* The receiving email address for the PDF file to be sent to.

* Ensure you inform Co-op Support if you need to change the receiving email.

* The intervals at which you would like patrons to receive notices.
+
The standard intervals to choose from are 1, 2, 3, 4, 5, 6, 7, 8, 9 or 10 weeks after the item becomes due. The intervals define when a second, third, or fourth, and so on, letter is sent out.
+
The 1 and 2 weeks overdue notices are sent to patrons without email address only. From the 3 weeks overdue notice onwards it is sent to all patrons.

* The wording you would like to be used on each notice.
+
This wording of the paper notices is customizable by library. PDF notices are set up by Co-op Support, and cannot be modified in the staff client. Please submit required revisions to Co-op Support.

CAUTION: A final notice which includes billing information can be set to coincide with the system
automatically marking long overdue items to lost. See xref:_final_notices[] for information on setting
up this notice


Overdue Notice by Phone
^^^^^^^^^^^^^^^^^^^^^^^^

You can set up a recurring report to generate a list of overdues for all patrons, or
for those without an email address only. Then you can phone each person individually.
You can specify an email address to receive an email reminder each time a list is generated.
There are shared templates for overdue reports in the *SITKA_templates -> Circulation* folder.
See xref:_shared_sitka_templates[] for more about using shared templates. Co-op
Support staff will be very happy to assist if you need help in this process.

Final Notices
~~~~~~~~~~~~~

The final paper overdue notice sent to patrons can be set as a billing notice which includes processing fees and replacement costs. The price is taken from the price entered in the price field of the copy editor for the item. If the price field is blank the price is taken from the Default Item Price setting in the Library Settings Editor. The processing fee comes from the Lost Materials Processing Fee setting found in the Library Settings Editor.

Final notices are set up as part of the paper overdues. When setting up your paper overdues specify the interval at which you would like the final notice to be sent and provide Co-op Support with the wording you would like to appear on the notice.

Libraries have the option to have Evergreen automatically mark long overdue items as lost. An email or paper notice will billing information may be sent to patrons. Contact Co-op Support if you would like to set this up for your library. Please include the interval at which you would like long overdue items to be marked as lost. This interval can be set to coincide with your final notice so that patrons receive a bill for lost items. This does not apply to items that are manually marked lost by staff.


Hold Notifications
~~~~~~~~~~~~~~~~~~

Hold Ready For Pickup
^^^^^^^^^^^^^^^^^^^^^

When a hold is ready for pickup, the requester can be notified via automatic email and/or SMS Text, and/or manual phone call by staff, depending on the choice made when he/she placed the hold. The selected notification method(s) may be indicated on the hold slip. For example, if email notification is selected, the email address will be printed on the hold slip. A blank email address indicates that email notification was not selected.

For automatic email notice and SMS Text, it works the same way as the automatic overdue notices. The notification email/SMS Text is generated and sent to the patron 5 to 30 minutes after the item achieves on-hold-shelf status. In order to receive these notices the patron must have chosen these notification methods when placing the hold, and the email address and or mobile number/carrier in his/her account must be valid.

The ready-for-pickup hold notification templates can be customized at the federation or library level. Please contact Co-op Support for customization.

For phone notification, staff needs to phone patrons individually. Phone numbers are printed on the hold slips when holds are captured, if phone notification is chosen.

Hold Expires from Hold Shelf Soon
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Holds Cancelled by Staff 
^^^^^^^^^^^^^^^^^^^^^^^^

This notification is optional for individual libraries. The notification templates can be customized on library level. Please contact Co-op Support if your library wishes to use this service.

An email is sent to the requester when a hold is cancelled by staff on the staff client. The staff note on cancellation will be included in the email explaining the cancellation reason.

Shelf Expired Holds Cancellation Notice
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

This notification is optional for individual libraries. The notification templates can be customized on library level. Please contact Co-op Support if your library wishes to use this service.

The emails are sent to the requesters when staff view and clear hold-shelf expired holds (click *Clear These Holds on Browse Holds Shelf*) on the staff client.

Hold Group Hold Placed for Patron Notice
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

This notification is optional for individual libraries. The notification templates can be customized on library level. Please contact Co-op Support if your library wishes to use this service.

The emails are sent to patrons when a new hold is placed through Hold Groups.

Patron Account Notices
~~~~~~~~~~~~~~~~~~~~~~

Welcome Email to New Patrons
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

An email will be sent to new patrons the day after their account is created, welcoming them to the library and confirming that the email address in their account is correct.

Patron Account Expiration Email
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

An email will be sent to patrons 30 days before their account is set to expire. This is intended to give users time to renew their account before they lose access to library services.

These emails are not spam and should not be marked as spam by either patrons or staff.

The two patron account notices are optional, and libraries must opt in. Libraries can choose to opt in to only one or both of these notices. The patron account notice templates can be customized at the federation or library level. Please contact Co-op Support for set up and customization.
