[[eg-self-check]]
Evegreen Self Check Administrative Set-up
-----------------------------------------

. Library sets up a computer specifically for self check with the following:
+
* a mouse
* a barcode scanner
* library security system (RFID pad, demagnetizing equipment, etc.)
* a keyboard
* a receipt printer
* Internet Browser
* The self check is known to be compatible with Chrome, Firefox and Internet Explorer.
* a method for locking down access so patrons cannot use the computer for other functions
* Co-op support recommends that you consult with your local IT support on the best method to lock down your computer.

. Library contacts Sitka Support to get a self check interface set up with the library's logo and colours.

. Co-op support supplies library with URL for self check and a self check specific Local System Administrator account.

. Library saves URL as a favourite in browser or as a shortcut on the computer's desktop for easy access.

. Library sets needed self check library settings. For details, refer to xref:lse-selfcheck[]

. Library teaches patrons to use self check.

. For instructions on using the native Evergreen Self Check, see xref:_self_check[]

CAUTION: The information in this section is specific to the native Evergreen Self Check which is available to all libraries. For information regarding a third party self check please contact the vendor.