When Will An Item Go In Transit?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(((Transit)))
(((In Transit)))

link:https://youtu.be/U3p2Ogif6xk[*Sitka Training Video - Transits (2:41)*]

Evergreen’s In Transit feature is used to keep track of items transferring among branches 
within a library system or between separate Sitka libraries. This functionality makes Interlibrary
Connect possible for BC and Manitoba public libraries and allows for BC OneCard returns to be tracked 
as they transit between Sitka BC public libraries.


. When an item is checked in at a non-owning branch or library, the status is changed to 
_In Transit_ and a transit slip is generated. Items in transit are sent to the destination 
branch or library according to your library’s policy and workflow.
. When you capture a hold with a pick up library other than your branch or library, the item’s 
status is changed to _In Transit_ and a hold transit slip is generated . Holds in transit are sent 
to the destination branch or library according to your library’s policy and workflow.

Libraries should check the xref:_transit_list[Transit List] on a regular basis for items that
have been in transit longer than normal or have been put into transit by misscans.

[TIP]
=====
If you capture holds on the _Capture Holds_ screen, a hold transit slip is printed 
automatically by default. If you capture holds on the _Check In_ screen, you can choose to 
print slips automatically by selecting the check in modifiers _Auto-Print Hold and Transit Slips_.
=====
