Circulation


-----------

* <<Check Out (F1)>>
~~~~~~~~~~~~~~

* <<Check In (F2)>>
~~~~~~~~~~~~~

* <<Renewing and Editing the Item's Due Date>>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* <<Marking Items Lost, Claimed Returned, and Claimed Never Checked Out>>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Note from Jennifer - do we want to split lost from claimed returned and claimed never checked out?  
We have a really long tip under lost that could then be incorporated into the main lost page

* <<In-House Use>>
~~~~~~~~~~~~

* <<Item Status>>
~~~~~~~~~~~

* <<Barcode Completion>>
~~~~~~~~~~~~~~~~~~

Besides the regular items in the catalogue, Sitka's Evergreen can circulate pre-catalogued and non-catalogued items too.

 * Regular circulation: circulation of regular items in your catalogue with a barcode.
 * Pre-catalogued , or pre-cat, circulation: circulation of items that have a barcode but have not been catalogued yet.  You may check them out and send for cataloguing after they are returned. Many Sitka sites use this functionality to circulate interlibrary loan items from other libraries. There is no need to route to cataloguing when using pre-cat for interlibrary loan, you can simply ignore the alert.

 *  Non-catalogued, or non-cat, circulation: circulation of items that are not in your catalogue and without a barcode.  These items are usually identified by categories, such as magazines, paperbacks, etc.
    