Holds Filling Explained
~~~~~~~~~~~~~~~~~~~~~~~
(((Holds Filling)))

When library staff or patrons initiate a hold through the staff or public catalogue, Evergreen checks all 
related library settings, hold policies, and holdings under the title, to decide whether or not
the hold can be placed.

If the hold can be placed Evergreen creates a hold request record which includes information such as
patron, pickup library, request time, and notification method and contact details.  


Selection Depth
^^^^^^^^^^^^^^^

Evergreen also records the range of libraries' items that may be used to fill the hold in the hold record.
This is recorded in the hold request record in a field called *Selection Depth*, which is viewable 
when viewing holds in either the patron's account or the title record.

The value in for *Selection Depth* will either be 2 or 3. 3 means the hold will be filled by items
belonging to the owning library or system.  2 means the hold can be filled by any holdable item within 
the library's reciprocal borrowing zone.

Selection depth is not editable and Evergreen will not reassess the selection depth when the holdability 
of items change. To change the selection depth for a hold staff have to manually cancel then place 
the hold anew.  A common situation where this may be needed if a library's item has gone missing and they
now want the hold to be filled by an interlibrary connect item.

Holds Targeter and Potential Targets
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

When a hold is placed Evergreen creates an eligible item table which includes all eligible items that could 
potentially fill the hold. This table is not viewable within the staff client.

In the first 24 hours after a hold is placed, Evergreen looks for potential items to add to 
the eligible item table approximately every about 15 minutes.  After the first 24 hours, Evergreen 
checks for eligible items once a day at approximately the time the hold was initially placed. 
The time is recorded in the hold request record in a field called *Previous Check Time*, which is 
viewable when viewing holds.  If a potential target is found, it will be added to the hold target table. 

While checking for eligible items to add to the table Evergreen is also retargeting the hold.  It does
this by removing the current target, checking the table, and picking another target, which may or may not
be the originally targeted item.  

When an item is checked in, Evergreen quickly goes through the eligible item table to see if the item
can fill a hold and captures it if it can.

When an eligible item has the status of _Available_ or _Reshelving_ Evergreen will add it to the 
library's pull list for hold requests. Though there may be multiple eligible items available, only 
one item may be put on the pull list at a time. If a different item is checked in first Evergreen will
opportunistically capture the hold and the item will disappear from the pull list.  Items will also disappear
from the pull list as Evergreen retargets holds daily and assigns new hold targets.

When there are multiple eligible items available, Evergreen will first choose the pickup 
library's copy, if available. Otherwise it will randomly pick up an item at another library, 
unless the pickup library imposes special rules prioritizing a preferred hold target source.

Newly catalogued items and items coming out of a non-holdable status (such as _Lost_) are not automatically
added to the eligible item table.  These items will be added when Evergreen does its daily check but 
libraries may prefer to force an earlier update of the table.  This is done by retargeting the hold.

[NOTE]
======
An item can be a potential target to fill a hold and still not be able to fill the hold.

For example, if an item is holdable, in a holdable shelving location, and has a holdable 
item status it is a potential target.  However, if the library that owns it is using 
age based hold protection the item cannot a hold at another library until the age based 
hold protection period is finished.
======


Holds Queue and Filling Sequence
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Holds are queued based on request time unless manually changed by library staff. 

Separate holds queues are formed based on the potential target item range. For example, there is a 
hold queue for item level holds and another for title level holds. If a hold is targeting your library's
item for pick up at your library then other libraries' holds are not counted in the queue of holds.

Item level holds have a simple queue, which includes all holds targeting the item. 

The title level holds queue counts all holds targeting any of the eligible items attached to that
particular bibliographic record that the title hold may target, including the item level holds. 
 You may notice missing queue numbers in item level holds queues; they are taken by the title level holds.

For libraries participating in reciprocal borrowing there will be separate queues based on the 
selection depth of the hold. Holds with a selection depth of 3 will have a separate queue based 
on the pickup library since they specially target the items owned by the pickup library. 
This means each library or system has its own queue if it has holdable copies.

Holds with a selection depth of 2 are queued together with the holds with a selection depth of 3 as items
from any library in the zone including the pickup library can fill the hold. When looking at  
You may see missing queue numbers in selection depth 3 holds queues, which are taken by selection 
depth 2 holds.

To view holds with a selection depth of 3 for your library simply filter the holds by pickup library, where the pickup
library is your library. The queue is arranged based on request time.  As you view the queue you may notice
that some queue numbers are missing.  This means there hold with a selection depth of 2 that is filling that
hold queue position.  
