Search the Public Catalogue
---------------------------

The Sitka catalogue can be accessed through the computers at your local library or online from any location via the Internet.

For online access, visit your library's website and follow the link to their online catalogue, or go to https://catalogue.libraries.coop for the BC Libraries Cooperative portal to the catalogue.



Basic Search
~~~~~~~~~~~~

The homepage for the Sitka catalogue allows you to search for books and other items at your library or libraries.

The homepage contains a single search box for you to enter a search term.


You can select to search by:

* Keyword—finds the terms you enter anywhere in the entire record for an item, including title, author, subject, and other information.
* Title—finds the terms you enter in the title of an item.
* Journal Title—finds the terms you enter in the title of a serial bibliographic record.
* Author—finds the terms you enter in the author of an item.
* Subject—finds the terms you enter in the subject of an item. Subjects are categories assigned to items according to a system such as the Library of Congress Subject Headings.
* Series—finds the terms you enter in the title of a multi-part series.

Formats
^^^^^^^

You can limit your search by format. Some of the more popular formats in the list are the following:

* For Books, you can choose _All Books_, which includes regular print books, large print books, and e-books, _All Audiobooks_, which includes audiobooks on physical media and e-audiobooks, OR you can choose the individual format. The individual choices are: _Books (physical)_, _Books (large print)_, _Books (electronic)_, _Audiobooks (physical)_ or _Audiobooks (electronic)_.
* For Videos, you can choose _All Videos_ which includes video formats such as DVD,VHS, Blu-ray, and E-video. OR you can choose the individual format. The individual choices are: _Videos (electronic)_ or _Videos (physical)_.
* _Music_ will search music on CD or other media.
* _Serials/Magazines_ will search for physical magazine, serial, or journal titles only.
* _Serials/Magazines (electronic)_ will search for electronic magazine, serial, or journal titles only.
* _Software/Video Games_ will search on games, databases, and other software.

Libraries
^^^^^^^^^

If you are using a catalogue in a library or accessing a library’s public catalogue from its homepage, the search will return items for your local library. If your library has multiple branches, the result will display items available at your branch and all branches of your library system separately. If your library participates in Interlibrary Connect the results may display items available across your federation.

If you access the catalogue from https://catalogue.libraries.coop, you may scope your search result to Sitka, regional libraries, a library system or a library branch by clicking into the Library box on the catalogue homepage and selecting the target library from the drop down list. You will then be able to see how many copies of a title are available in all Sitka member libraries across Sitka, or within the regional libraries, or within the library system, or within the branch, depending on search scope selected

Advanced Search
~~~~~~~~~~~~~~~

You can access the Advanced Search by clicking *Advanced Search* on the catalogue homepage or search results screen.

The available search options are the same as on the homepage, but you may use one or more of them simultaneously. If you want to combine more than three search options, use the *Add Search Row* button to add more search input rows. Clicking the *X* button will close the search input row.


Search Library
^^^^^^^^^^^^^^

The current search library is displayed in the _Search Library_ box. If you access the catalogue from your library's homepage or catalogue URL, the default search library is your library or borrowing zone. If your library system has multiple branches or a borrowing zone that includes multiple libraries you can use the _Search Library_ box to select different branches or libraries.

If you access the catalogue from https://catalogue.libraries.coop, your default search library is Sitka or the library you have selected on the homepage. You may use the _Search Library_ box to select a different library or regional libraries, or all libraries in Sitka to search.

Sort Results
^^^^^^^^^^^^

By default, the search results are in order of greatest to least relevance. See OPAC Order of Results. In the _Sort Results _box you may select to order the search results by relevance, title, author, publication date, or popularity.

Limit to Available
^^^^^^^^^^^^^^^^^^

When the _Limit to Available_ checkbox is checked search results are limited based on an item’s current circulation status. Titles without available items in the selected search library will not be displayed. Item statuses that show as available are: _Available_, _On Display_, _Onsite Consultation_, _Reserves_, and _Reshelving_.

Group Formats and Editions
^^^^^^^^^^^^^^^^^^^^^^^^^^

When the _Group Formats and Editions_ checkbox is checked all formats and editions of the same title are grouped as one result. For example, the DVD and the first and second print editions of Harry Potter and the Chamber of Secrets will appear together.

Exclude Electronic Resources
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

When the _Exclude Electronic Resources_ checkbox is checked electronic resources are not included in the search results.

Search Filter
^^^^^^^^^^^^^

You can filter your search by:

* Format
* Language
* Audience
* Literary Form
* Publication Year
** Publication year is inclusive. For example, if you set Publication Year Between 2005 and 2007, your result items will be published in 2005, 2006 and 2007.
* Shelving Location
** Shelving Locations that are not OPAC visible will not be displayed

Numeric Search
~~~~~~~~~~~~~~

You can access the Numeric Search by clicking on the *Numeric Search* tab on the _Advanced Search_ screen.

Use the drop-down menu to select ISBN, ISSN, Call Number, LCCN, TCN, or Item Barcode. Enter the information and click *Search*.


Searching by Call Number will take you to the Shelf Browser.

MARC Expert Search
~~~~~~~~~~~~~~~~~~

You can access the MARC Expert Search by clicking on the *Expert Search* tab on the Advanced Search screen.

If you are familiar with the MARC standard, you may search by tag in the Expert Search. Enter the three-digit tag number, the subfield (if relevant), and the value or text that corresponds to the tag. For example, to search by publisher name, enter 260 b Random House. To search several tags simultaneously, use the *Add Row* option. Click *Search* to run the search.

Browse the Catalogue
~~~~~~~~~~~~~~~~~~~~

You can access the browse search clicking *Browse the Catalogue* on the catalogue homepage or search results screen.

Patrons and staff can browse records in the catalogue. The following fields are browsable: title, author, subject, and series. The browse is constructed by the term starting with. To browse the catalogue, click *Browse the Catalogue*, select a field to browse, and enter a keyword and click *Browse*. A list of results will appear. Click on the bolded text to view bibliographic records. You may move backward or forward through your results by clicking on *Back* or *Next*. Note your results are alphabetical, with results prior to your search term, and after, listed.
