Holdings
--------

System Generated Holdings Statement
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
As issues are received, Evergreen creates a holding statement in the OPAC based on what is set up in the Caption and Patterns of the subscription. The systems generated holdings can only be edited by changing caption and pattern information and there is no ability to edit the statement as free text.


MFHD Records
~~~~~~~~~~~~

MARC Format for Holdings Display (MFHD) display in the catalog in addition to holding statements generated by Evergreen from subscriptions created in the Serials Module. The MFHDs are editable as MARC but the holdings statements generated from the control view are system generated. Multiple MFHDs can be created and are tied to Organizational Units.

Evergreen users can create, edit and delete their own MFHD.

Create an MFHD record
^^^^^^^^^^^^^^^^^^^^^

To create a MFHD record:

From a serials record in the catalog, go to *Serials* -> *Manage MFHDs*. This will bring you to the Manage MFHD tab within the serials module.

. Click *Create MFHD*.
. A Create new MFHD dialog box will appear. Select the library for which you are creating the MFHD record and click Create.
. The MFHD record will appear in the list.
. Click *Actions* -> *Edit MFHD*
. The MARC Editor will appear. Modify the MFHD record as needed and click *Save*.
. The Textual Holdings statement will appear in the Issues Held tab in the catalog.

Edit a MFHD record
^^^^^^^^^^^^^^^^^^

. Open a serial record, go to *Serials* -> *MFHD Record* -> *Manage MFHDs* and select the appropriate MFHD.
. Click *Actions* -> *Edit MFHD*.
. The MARC Editor will appear. Modify the MFHD record as needed and click *Save*.

Delete a MFHD Record
^^^^^^^^^^^^^^^^^^^^

. Open a serial record, go to *Serials* -> *MFHD Record* -> *Manage MFHDs* and select the appropriate MFHD.
. lick *Actions* -> *Delete Selected MFHDs*.
. Click OK/Continue to delete the record.
