Serials Binding
---------------

Apply a Binding Template
~~~~~~~~~~~~~~~~~~~~~~~~

To bind issues, first a binding template needs to be applied to the associated 
Distribution.

. Go to the *Manage Subscriptions* tab and from the grid, select the distribution(s) with issues you’d like to 
bind.
. Right-click on the distribution(s) or go to *Actions* and select *Apply Binding Template*.
. In the dialog box that appears, select the Serial Copy Template you’d like to use from the dropdown 
and click *Update*.


Bind Received Issues Together
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

. Go to the *Manage Issues* tab and select the issues you want to bind together.
. Right-click on the issues or go to *Action* and select *Bind*.
. The Bind Items interface will appear and all items will be represented on the screen. The first item’s fields will be editable.
. Modify the Call Number if needed.
. Replace the Barcode and click Save.

NOTE: The barcode must be replaced with a new barcode. The binding will fail if you attempt to reuse an existing barcode from one of the items being bound. Evergreen views it as a duplicate barcode.
