Serials Administration
----------------------

Serials Permissions
~~~~~~~~~~~~~~~~~~~

Serials permissions are required to use the Serials Module. If your library is interested in using the Serials module please contact Sitka Support.

Serial Copy Templates
~~~~~~~~~~~~~~~~~~~~~~

Serial Copy Templates specify the item attributes that should be applied when a serial copy is received. You must create at least one template to receive serials.

Create a Serial Copy Template
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

. Click *Administration* -> *Serials Administration* -> *Serial Copy Templates*.
. Click *Create Template*.
. Enter a _Template Name_.
. Choose the item attributes for this template.
. Click *Save*.

Edit a Serial Copy Template
^^^^^^^^^^^^^^^^^^^^^^^^^^^

. Click *Administration* -> *Serials Administration* -> *Serial Copy Templates*.
. Click the check box beside the template you want to edit.
. Click *Actions* -> Choose _Edit Template_.
. Edit the item attributes for this template.
. Click *Save*.

Delete a Serial Copy Template
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

. Click *Administration* -> *Serials Administration* -> *Serial Copy Templates*.
. Click the check box beside the template you want to delete.
. Click *Actions* -> Choose _Delete Template_.

NOTE: Serial Copy Templates that are being used by subscriptions cannot be deleted.

Prediction Pattern Templates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Create a Prediction Pattern Template
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

. Click *Administration* -> *Serials Administration* -> *Prediction Pattern Templates*.
. Click *New Record*.
. Enter a _Name_.
. Click *Pattern Wizard*.
.. See xref:pattern-wizard[] for detailed steps.
. Choose the _Owning Library_.
. Choose the _Share Depth_.
. Click *Save*.

[[pattern-wizard]]
Pattern Wizard
++++++++++++++

. Enumeration Labels
.. Click *Next*
. Chronology display
.. Click *Next*
. MFHD Indicators
.. Click *Next*
. Frequency and Regularity
.. Click *Next*
. Review
.. Click *Save*

Edit a Prediction Pattern Template
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

. Click *Administration* -> *Serials Administration* -> *Prediction Pattern Templates*.
. Click the check box beside the template you want to edit.
. Click *Actions* -> Choose _Edit Template_.

NOTE: Prediction Patterns can be edited after creation as long as all predicted issues have the status of "Expected". Once an issue is moved into a different status, the Prediction Pattern cannot be changed.

Delete a Prediction Pattern Template
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

. Click *Administration* -> *Serials Administration* -> *Prediction Pattern Templates*.
. Click the check box beside the template you want to delete.
. Click *Actions* -> Choose _Delete Template_.

NOTE: Prediction Pattern Templates that are being used by subscriptions cannot be deleted.


Serials Specific Settings in the Library Settings Editor
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Click *Administration* -> *Local Administration* -> *Library Settings Editor*.

The following settings should be configured in the Library Settings Editor before you start using the Serials module.

|======================
|Group|Setting|Description|Options|Notes
|Serials|Default display grouping for serials distributions presented in the OPAC| | "enum" or "chron" | *enum* should display in the OPAC volume and number by month and year / *chron* will display in the OPAC by month  .
|Serials|Previous Issuance Copy Location|When a serial issuance is received, copies (units) of the previous issuance will be automatically moved into the configured shelving location|   | use this setting to specify a default copy location for serials
|OPAC| Use fully compressed serials holdings |    | "true" or "false" | *true* is recommended
|======================
